blocksToDig:
  BEDROCK:
    hardness: 1.5

itemsToDigWith:
  DIAMOND_PICKAXE: # Must be caps and exact same as item is named in game
    isHarvestable: true
    isBestTool: true
    MinEnchantment: # If any of the below are true >= given lvl then its ok to break
      sharpness: 1,
      fatigue: 23
    ExactEnchantment: # All below must be true, however if any MinEnchantment is true then this is redundant
      unbreaking: [3,1]
    #PERMISSION:
    #  normal player or smth - Links to toggle.bb or whatever that is

# Also add:
# isHarvestable (true - The digged block will give a drop when it breaks) (True if not set)
# isBestTool (true - It will dig the block faster, ie dirt is mined faster by shovel than pick) (true if not set
